version: 1
formatters:
  default:
    class: uvicorn.logging.DefaultFormatter
    format: '{"level":"%(levelname)s","timestamp":"%(asctime)s","name":"%(name)s","message":"%(message)s"}'
  access:
    class: uvicorn.logging.AccessFormatter
    format: '{"level":"%(levelname)s","timestamp":"%(asctime)s","name":"%(name)s","client_addr":"%(client_addr)s","request_line":"%(request_line)s","status_code":"%(status_code)s"}'
handlers:
  default:
    formatter: "default"
    class: "logging.StreamHandler"
    stream: "ext://sys.stderr"
  access:
    formatter: "access"
    class: "logging.StreamHandler"
    stream: "ext://sys.stderr"
loggers:
  gunicorn:
    level: "INFO"
    handlers:
      - "default"
  gunicorn.error:
    level: "INFO"
    handlers:
      - "default"
  gunicorn.access:
    level: "INFO"
    propagate: False
    handlers:
      - "access"
root:
  level: "INFO"
